### ISSUE TITLE
扫描不到匹配设备

### ISSUE THREAD

**Issue by WAWXuan** [celesWuff/waterctl#1]
手机里蓝牙可以看到设备，但是在浏览器里扫描就扫不到东西

**Comment by celesWuff** [comment]
了解。需要补充更多信息：

- 手机的系统版本（若你的手机使用 MIUI/EMUI/OneUI 等定制系统，也请一并附上它们的版本）
- 浏览器版本
- 水控器的蓝牙名称

如果你的水控器蓝牙名称不是以“Water”开头，则很有可能无法使用本项目。

**Comment by WAWXuan** [comment]
手机的系统版本 安卓11 MIUI12
浏览器版本 Edge 46.03.4.5155
水控器的蓝牙名称 BFCB5B

**Comment by celesWuff** [comment]
如果你确定水控器由常工电子开发，可以使用下面这个版本试试手气。
https://water-next.celes.workers.dev/
目前，这个版本会显示所有可供连接的蓝牙设备。

如果这个版本也不好使，本项目将无能为力。
（由于缺乏测试设备，我们不太可能很快开发出能用的成品。）

**Comment by WAWXuan** [comment]
连接后报错，可能我的水控器不是由常工电子开发(可能是广州好年华)，只是在常工电子官网客户案例里看到了我们学校，尝试一下能否使用
![IMG_20210407_222011](https://user-images.githubusercontent.com/66638955/113882724-2003d780-97f0-11eb-824a-32180a8b0ffa.jpg)

**Comment by celesWuff** [comment]
很有可能。这个错误只会在连接非常工电子水控器的蓝牙设备时出现。目前没有支持其他品牌水控器的计划。

（才发现常工电子的官网有列出应用案例。他们那个案例列表完全是乱来……）
