### ISSUE TITLE
大哥ipad的bluefy突然打不开热水器了，电脑连接时间也变长了，自动连接两次才连上

### ISSUE THREAD

**Issue by hhyrhac** [celesWuff/waterctl#10]
大哥ipad的bluefy突然打不开热水器了，电脑连接时间也变长了，自动连接两次才连上

**Comment by celesWuff** [comment]
如果重复连接可以正常使用，则可能单纯是信号不良导致的。

对于 Bluefy，目前无法复现。如果您持续遇到该问题，可以考虑在 App Store 寻找其他支持蓝牙的浏览器，如 Path Browser。
