### ISSUE TITLE
有人来宿舍更新系统，由原来的累积用水量变成扣除用水量的计数方法

### ISSUE THREAD

**Issue by ThreeN0350** [celesWuff/waterctl#15]
然后就不能使用了，这种需要重新编程吗，有大神会吗，有偿

**Comment by fusufusu** [comment]
求更新

**Comment by Branches01** [comment]
更新后无法使用，目前不知什么原因，链接的时候响了一声，过了一两秒连着响几声，估计是断开链接了。反正用不了，求更新。

**Comment by Marlboro8** [comment]
求更新

**Comment by baiwangongchengshi** [comment]
通过控制**计数器**与**脉冲值**实现自定义余数稳定控制已实现，但我听说有**更好的控制方法**，坐等大佬开源分享

**Comment by Branches01** [comment]
> 通过控制**计数器**与**脉冲值**实现自定义余数稳定控制已实现，但我听说有**更好的控制方法**，坐等大佬开源分享
能否开源

**Comment by ThreeN0350** [comment]
有方法了，不需要编程。方法如下：拆开热水控制盒子，拔掉小的那个插头（里面有一大一小两个插头），然后用学校的热水小程序连接，就能出热水了，然后是不会扣钱的。贴吧上的那个大概率是这个方法，还卖 50 块，发钱寒。

**Comment by liao2273972416** [comment]
> 有方法了，不需要编程。方法如下：拆开热水控制盒子，拔掉小的那个插头（里面有一大一小两个插头），然后用学校的热水小程序连接，就能出热水了，然后是不会扣钱的。贴吧上的那个大概率是这个方法，还卖 50 块，发钱寒。

佛大的？成功了吗

**Comment by MoYuRuan** [comment]
> > 有方法了，不需要编程。方法如下：拆开热水控制盒子，拔掉小的那个插头（里面有一大一小两个插头），然后用学校的热水小程序连接，就能出热水了，然后是不会扣钱的。贴吧上的那个大概率是这个方法，还卖 50 块，发钱寒。
> 
> 佛大的？成功了吗

成了，随便用

**Comment by csdcsdcsdcsd** [comment]
> 通过控制**计数器**与**脉冲值**实现自定义余数稳定控制已实现，但我听说有**更好的控制方法**，坐等大佬开源分享

大佬能分享一下吗qaq

**Comment by celesWuff** [comment]
想我了吗？

**Comment by Hopose** [comment]
> 想我了吗？

- 大佬孩子们想你啦(ಥ﹏ಥ)

**Comment by celesWuff** [comment]
在做了在做了

如果您希望提供其他不便公开的信息，可致信 celeswuff@protonmail.com

引流位：我们正在开发一个研究用途的水控器模拟器，欢迎参与协助。
https://github.com/celesWuff/wateremu

**Comment by celesWuff** [comment]
我们发布了适配新固件的首个测试版本，敬请反馈使用体验。

由于离线缓存的原因，可能需要先刷新几次，再使用。

注意，当前不是完美实现，有以下几点需要注意：

1. 需要先移除对设备的硬破。硬破状态下无法统计用水量，仍会导致 7 分钟断开，~~并可能触发下面所描述的设备锁定。~~
2. （已解决）~~应尽量避免连接后不开闸使用就断开。若短时间内多次连接再断开，且没有用水量时，可能导致设备锁定：错误码 err05 并且使 waterctl 失效。~~
3. （已解决）~~即使正常使用也可能有极小概率触发设备锁定。~~
4. ~~若已经发生设备锁定，使用官方小程序连接并消费至少 0.01 元来解锁。~~

我们仍在探索完美实现的可行性。

**Comment by Branches01** [comment]
> 我们发布了适配新固件的首个测试版本，敬请反馈使用体验。
> 
> 由于离线缓存的原因，可能需要先刷新几次，再使用。
> 
> 注意，当前不是完美实现，有以下几点需要注意：
> 
> 1. 需要先移除对设备的硬破。硬破状态下无法统计用水量，仍会导致 7 分钟断开，并可能触发下面所描述的设备锁定。
> 2. 应尽量避免连接后不开闸使用就断开。若短时间内多次连接再断开，且没有用水量时，可能导致设备锁定：错误码 err05 并且使 waterctl 失效。
> 3. 即使正常使用也可能有极小概率触发设备锁定。
> 4. 若已经发生设备锁定，使用官方小程序连接并消费至少 0.01 元来解锁。
> 
> 我们仍在探索完美实现的可行性。

试了不能用，不知道错误信息，所以无法为你提供错误原因。链接的时候会“嘀”一声，过了几秒会连续“嘀”几声。不知道其他人能否使用。

**Comment by celesWuff** [comment]
已发布新版本尝试解决此问题，期待您的反馈。

**Comment by Hopose** [comment]
> 已发布新版本尝试解决此问题，期待您的反馈。

第一次链接以后是可以使用了，但是没有正常停止后，再链接就显示error了。可能就需要等到机器自动断开之后，才能链接上。

**Comment by sip0724** [comment]
可以用呀 显示800多l 也可以正常关

**Comment by siyiovo** [comment]
配对完成后发现页面会一直卡在”请稍后“这，连不上

**Comment by Branches01** [comment]
> 已发布新版本尝试解决此问题，期待您的反馈。

链接后显示err39仍无法使用
<img width="1274" alt="mmexport1714197100264" src="https://github.com/celesWuff/waterctl/assets/167621582/91f487be-9c44-4300-801e-fa640614f1ad">

**Comment by celesWuff** [comment]
@Hopose @siyiovo 很抱歉我在尝试修复最开始的 bug 的时候无意间引入了另一个 bug，现在应该已经都修复了。在网络通畅的情况下多刷新一次即可更新到最新版本。

@Branches01 我想不明白这个错误是如何可能出现的……您能用现在的版本再试试看吗？

**Comment by siyiovo** [comment]
感谢大佬！可以正常使用了！ @celesWuff

**Comment by Branches01** [comment]
> @Hopose @siyiovo 很抱歉我在尝试修复最开始的 bug 的时候无意间引入了另一个 bug，现在应该已经都修复了。在网络通畅的情况下多刷新一次即可更新到最新版本。
> 
> @Branches01 我想不明白这个错误是如何可能出现的……您能用现在的版本再试试看吗？

可以用了，没问题了，谢谢

**Comment by lzhello** [comment]
<img width="852" alt="c8f97f5d0dd48a1193ca4b5341f10ba" src="https://github.com/celesWuff/waterctl/assets/145476864/8064d407-e4a8-46e1-bddf-b54628095557">请问这种情况怎么办

**Comment by lzhello** [comment]
> <img alt="c8f97f5d0dd48a1193ca4b5341f10ba" width="852" src="https://private-user-images.githubusercontent.com/145476864/326170869-8064d407-e4a8-46e1-bddf-b54628095557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTQ2MDgsIm5iZiI6MTcxNDIxNDMwOCwicGF0aCI6Ii8xNDU0NzY4NjQvMzI2MTcwODY5LTgwNjRkNDA3LWU0YTgtNDZlMS1iZGRmLWI1NDYyODA5NTU1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QxMDM4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjQxOTNmNmY5NmYzMDJlMWRmMmYyZjY0Nzg0ZjE0MTQ4Mjk5NWNhNGNhYWNiNTBmODc0NWRlNGQzOTk1NWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K3IscBoRdyR30_KEwatRHnVBcscSHH83gUGYMpa3ZfU">请问这种情况怎么办

**Comment by asdmao** [comment]
> <img alt="c8f97f5d0dd48a1193ca4b5341f10ba" width="852" src="https://private-user-images.githubusercontent.com/145476864/326170869-8064d407-e4a8-46e1-bddf-b54628095557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMjU3NDMsIm5iZiI6MTcxNDIyNTQ0MywicGF0aCI6Ii8xNDU0NzY4NjQvMzI2MTcwODY5LTgwNjRkNDA3LWU0YTgtNDZlMS1iZGRmLWI1NDYyODA5NTU1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QxMzQ0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTg3OWExMWViOWY3MzAzNjdkNWExMGEyYzMxZTk4YTM0ODljZGEyNTI2OTcyYWFjOWY5MjVlMzYwNGExZDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U6ynUbVsCE7tJnrHuIa3spAH4vBWAAo1DiLzI61BZeI">请问这种情况怎么办

没更新水控的宿舍，只能连成功一次，后面就是和这个图片一样了，这是正常的吗？

**Comment by Kenryy** [comment]
连接后会出现err39并伴随嘀嘀嘀报错，但不用担心，耐心稍等两秒你就能享受八百多升的热水👍
想要重连可以尝试断电重开

**Comment by lzhello** [comment]
> 连接后会出现err39并伴随嘀嘀嘀报错，但不用担心，耐心稍等两秒你就能享受八百多升的热水👍 想要重连可以尝试断电重开

这个就是一直在这里连不上去了

**Comment by celesWuff** [comment]
~~我真傻，真的~~
现在应该都已经修复了，并且我们重新启用了版本号，左下角会显示当前的版本号。
截至目前，最新的版本是 1.1.3。
