### ISSUE TITLE
宿舍更新系统后，出现bug了

### ISSUE THREAD

**Issue by STAR-K-007** [celesWuff/waterctl#16]
有人来宿舍更新系统后，用不了了出现了bugSecurityError: Failed to execute 'requestDevice' on 'Bluetooth': Must be handling a user gesture to show a permission request. 求大神更新

**Comment by tamikip** [comment]
佛大的？

**Comment by Marlboro8** [comment]
佛大小登没热水用了

**Comment by xaiolongkhhd** [comment]
感觉不是这个问题，要在写入负载那个star函数改成每次连接都有100l水应该可以

**Comment by Dd41212** [comment]
大佬，能重新破一下佛大的蓝牙热水器吗

**Comment by voyage01969** [comment]
佛大学子＋10086，很需要大佬更新/(ㄒoㄒ)/~~

**Comment by Ncver740** [comment]
佛山老登+1

**Comment by 959611** [comment]
同佛大的，连接之后水控会连响几声并显示err39，求大佬更新QWQ

**Comment by Ncver740** [comment]
佛大同求

**Comment by liao2273972416** [comment]
佛大的，求大佬更新

**Comment by NotSayingSecret** [comment]
现在连接蓝牙后显示err39，望大神出手！！

**Comment by celesWuff** [comment]
我们正在尝试解决此问题。详见：https://github.com/celesWuff/waterctl/issues/15#issuecomment-2078963008
