### ISSUE TITLE
拆开了不知道拔哪里> > 有方法了，不需要编程。方法如下：拆开热水控制盒子，拔掉小的那个插头（里面有一大一小两个插头），然后用学校的热水小程序连接，就能出热水了，然后是不会扣钱的。贴吧上的那个大概率是这个方法，还卖 50 块，发钱寒。

### ISSUE THREAD

**Issue by csdcsdcsdcsd** [celesWuff/waterctl#17]
> > 有方法了，不需要编程。方法如下：拆开热水控制盒子，拔掉小的那个插头（里面有一大一小两个插头），然后用学校的热水小程序连接，就能出热水了，然后是不会扣钱的。贴吧上的那个大概率是这个方法，还卖 50 块，发钱寒。
> 
> 佛大的？成功了吗

成了，随便用

_Originally posted by @SaBiRuan in https://github.com/celesWuff/waterctl/issues/15#issuecomment-2074575881_

**Comment by Kenryy** [comment]
体验不太行，每7分钟会断一次

**Comment by YingYeGui** [comment]
有好几个头那根线啊？

**Comment by redswan233** [comment]
那个卖五十块钱的我也是无语，靠学校发财还骂学校，说他一下就骂我是学校的走狗

**Comment by MoYuRuan** [comment]
> 有好几个头那根线啊？

盒子里面就俩头，一个大的一个小的，插在电路板上，拔掉小的那个就行

**Comment by MoYuRuan** [comment]
> 有好几个头那根线啊？

盒子里面就俩头，一个大的一个小的，插在电路板上，拔掉小的那个就行

**Comment by voyage01969** [comment]
其实可以不同拆也可以免费连，只不过体验也不太好（

**Comment by KHShum75365** [comment]
> 其实可以不同拆也可以免费连，只不过体验也不太好（

请问该如何操作

**Comment by voyage01969** [comment]
> > 其实可以不同拆也可以免费连，只不过体验也不太好（
> 
> 请问该如何操作
有些问题还没完全解决，不过本质上就是离线开热水器就行

**Comment by KHShum75365** [comment]
> > > 其实可以不同拆也可以免费连，只不过体验也不太好（
> > 
> > 
> > 请问该如何操作
> > 有些问题还没完全解决，不过本质上就是离线开热水器就行

是断网用小程序连吗

**Comment by voyage01969** [comment]
> > > > 其实可以不同拆也可以免费连，只不过体验也不太好（
> > > 
> > > 
> > > 请问该如何操作
> > > 有些问题还没完全解决，不过本质上就是离线开热水器就行
> 
> 是断网用小程序连吗

对的，不过每次只能用25.6L，用完会断，要重新再连。

**Comment by KHShum75365** [comment]
> > > > > 其实可以不同拆也可以免费连，只不过体验也不太好（
> > > > 
> > > > 
> > > > 请问该如何操作
> > > > 有些问题还没完全解决，不过本质上就是离线开热水器就行
> > 
> > 
> > 是断网用小程序连吗
> 
> 对的，不过每次只能用25.6L，用完会断，要重新再连。

感谢

**Comment by Wenyase** [comment]
> 体验不太行，每7分钟会断一次
目前推测是这个的原因，那个小插头估计是检测水流的。
![jietu](https://github.com/celesWuff/waterctl/assets/125632177/ab0901e9-8b3d-40b9-88d6-4ef7e555d96c)

**Comment by celesWuff** [comment]
我们正在尝试解决此问题。详见：https://github.com/celesWuff/waterctl/issues/15#issuecomment-2078963008

**Comment by voyage01969** [comment]
> 我们正在尝试解决此问题。详见：[#15 (comment)](https://github.com/celesWuff/waterctl/issues/15#issuecomment-2078963008)

非常感谢大佬，问题已解决，好人一生平安！！
