### ISSUE TITLE
求教一下

### ISSUE THREAD

**Issue by wulu007** [celesWuff/waterctl#18]
作者是通过提取固件的方式，来进行实现的，还是其他方式

**Comment by Penguinchat** [comment]
LOL，我猜是通过试代码啦，总不可能专门买一台机子吧

**Comment by wulu007** [comment]
> LOL，我猜是通过试代码啦，总不可能专门买一台机子吧

可以把学校的给拆了😂

**Comment by Penguinchat** [comment]
> > LOL，我猜是通过试代码啦，总不可能专门买一台机子吧
> 
> 可以把学校的给拆了😂

你拆了寄给大佬，保证一天之内给你破了：）

**Comment by biguniversity** [comment]
作者太强了,可以说下更新是改了什么才能够成功的吗

**Comment by wulu007** [comment]
> 作者太强了,可以说下更新是改了什么才能够成功的吗

新固件加了一个验证机制，需要往F1F1写一个数据才能用启动命令

**Comment by NotSayingSecret** [comment]
卧槽，太厉害这个作者，收到我们的反馈真去改了，真做到了像他签名所说那样，实在佩服。

**Comment by Penguinchat** [comment]
tip，新版软件能正常开启热水控，但无法关闭，只能通过让热水器7分钟无水流自动关闭 @celesWuff
