### ISSUE TITLE
现在会出现这个bug而且出不了热水

### ISSUE THREAD

**Issue by cce20031122** [celesWuff/waterctl#20]
![Uploading 0bfa59d700f674b6d5c380f490de3c6.png…]()

**Comment by cce20031122** [comment]
调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B01CDB01FF000C0E240429202739260100
TXD: FEFE09B201B5FE0070E2EB2001010000006C3000
RXD: FDFD09C8500200AA

**Comment by cce20031122** [comment]
现在搜索会搜到其他的蓝牙设备比如手环

**Comment by celesWuff** [comment]
请告知我您使用的小程序是哪一个，曾经是否可以使用 waterctl，如果是，从什么时候开始失效的？是否可能和 issue #4 #9 #11 #12 为相同问题？

如需分享敏感信息（如学校名称），请致信 celeswuff@protonmail.com。

**Comment by celesWuff** [comment]
已发布 1.1.6 尝试解决此问题，期待您的反馈。

**Comment by cce20031122** [comment]
现在可以出热水了，非常感谢！
