### ISSUE TITLE
2024年5月6日，还是使用不了，如图

### ISSUE THREAD

**Issue by asdmao** [celesWuff/waterctl#21]
![QQ图片20240506182229](https://github.com/celesWuff/waterctl/assets/168282579/e566eb1c-6083-4915-ae80-96674dd56b90)

**Comment by asdmao** [comment]
![Uploading QQ图片20240506182236.png…]()

**Comment by asdmao** [comment]
![QQ图片20240506182236](https://github.com/celesWuff/waterctl/assets/168282579/78290520-2788-4ef0-98f1-f22a3490dcb0)

等待时间似乎太长了。

如果该问题反复发生，这可能是一个 Bug，请截图并[反馈给开发者](https://github.com/celesWuff/waterctl)。

调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B01A12020B00488B240505213451440200
TXD: FEFE09BC0000
TXD: FEFE09BB00000000000000200101000000002000
TXD: FEFE09B2015D670070E2EB2001010000006C3000

**Comment by asdmao** [comment]
五月一号二号三号四号还可连接使用，从五号开始出现如图的问题无法使用

**Comment by celesWuff** [comment]
已发布 1.1.7，增大了几个指令间的等待延迟，希望能够修复此问题。

**Comment by asdmao** [comment]
[image: QQ图片20240507172124.png]
1.1.7仍无法解决本宿舍无法连接的问题，但我好像发现了问题所在
先说结论：我们宿舍的水控器被学校遗漏了，没升级成最新的

我使用学校官方小程序去连接自己宿舍的，是从0开始递增，这是升级前的状态；
[image: QQ图片20240507173204.png]

用官方程序连接上午测试的另一个宿舍，是显示还可以用多少水，递减，也是水控器升级后的状态；
[image: QQ图片20240507173200.png]
希望大佬可以上传个v1.1.5版本的水控程序，那个版本在四月二十九三十和五一二三这几天可以被本宿舍链接并使用，貌似新旧兼容（？）或者上传个没升级前的程序

附1
v1.1.7也就是最新的这一版，上午用来测试的宿舍，现在仍可以正常使用，又连了其他附近几个宿舍（有显示在上面的）也可连接成功，只有我们宿舍连不上
附2
感谢大佬的隐私信息提醒，本次图片均是截图发到qq群再保存的，应该没有泄露信息了吧（笑）




celesWuff ***@***.***> 于2024年5月7日周二 14:53写道：

**Comment by WNHW** [comment]
同问题，我们宿舍的计数方式也是从零开始向上递增，也是在五月五日那天以后无法正常使用。或许真的是楼主说的那样上下不兼容了qwq

**Comment by celesWuff** [comment]
@asdmao 您的附件没有上传成功。
此外，以防您没有留意到，您正在 GitHub 上发表公开回复，而非回复我的邮件。

<img src="https://github.com/celesWuff/waterctl/assets/81074567/346d1dcc-ec45-4c7c-8567-7acf01ac7cd3" width="500" height="500" />

**Comment by celesWuff** [comment]
已发布 1.1.8，应该已经修复。

**Comment by NotSayingSecret** [comment]
现在5月27，所以是确定没有办法破解了吗？呜呜
