### ISSUE TITLE
24年5月27，更新之后又不行了

### ISSUE THREAD

**Issue by 1994789147** [celesWuff/waterctl#26]
出现错误
等待时间似乎太长了。

如果该问题反复发生，这可能是一个 Bug，请截图并反馈给开发者。

调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B01503000B003C42240527233047000000
RXD: FDFD09AE23000037846903040506070809101112
TXD: FEFE09BC0000
TXD: FEFE09BB00000000000000240527233544002000
TXD: FEFE09B2016DBFFF0000002405272335450F2700

**Comment by Rongzr2** [comment]
> 想你了，牢大

**Comment by celesWuff** [comment]
#34
