### ISSUE TITLE
_

### ISSUE THREAD

**Issue by MoYuRuan** [celesWuff/waterctl#28]

**Comment by MoYuRuan** [comment]
物理破解的热水器将不会计算流水量，依然只能使用7分钟。

**Comment by MoYuRuan** [comment]
rsosrosrshrhoorrhrssrhohhsrsohorososhshrsrohhosorrorsshhsrsorhrhhrhshrsrosohrhhhorrrosrohoshrrorhhrshrssssrrorsrorrrshhoosrosoorssrsssoooohhoorsororhoohoooosrrosrrshrhhhhrhhssroshsrhohhsrosshooshssohshooroohhsoorhrhhsosoohrroohssrhossshrshhsrsrrsrsrrhohsoorrhh

**Comment by MoYuRuan** [comment]
dwwndnppdwdnpdwpnpdpwpwnwndwdpnnpwpddpwpdndnndnwndwnnpdddpwdpnpwnddpdnndwndwwwwddpdnnppwwppppnnppdwpdpdnpwddpwddwndpwnwdnpnnwdpwwnppwnwwpnwnppdppnnwppdndnnwpwppnddppnwwdnpwwwndwnnwdwddwdwddnpnwppddnn

**Comment by wulu007** [comment]
你是不是被抓了😂

**Comment by MoYuRuan** [comment]
<img width="164" alt="mmexport1710027478261" src="https://github.com/celesWuff/waterctl/assets/139094453/b80a231f-3659-40a4-8b6d-30a25f95e75b">

**Comment by Kenryy** [comment]
怎么找到你的🤭
