### ISSUE TITLE
佛大用不了了！！！

### ISSUE THREAD

**Issue by I-LOVE-DY** [celesWuff/waterctl#30]
等待时间似乎太长了。

如果该问题反复发生，这可能是一个 Bug，请截图并[反馈给开发者](https://github.com/celesWuff/waterctl)。

调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B180000000
RXD: FDFD09AE7E000004910103040506070809101112
TXD: FEFE09BC0000
TXD: FEFE09BB01010D00500198240601165033002000
TXD: FEFE09B2012CCAFF0031112406011650340F2700

**Comment by n-sadext** [comment]
佛大用不了！

**Comment by n-sadext** [comment]
等待时间似乎太长了。

如果该问题反复发生，这可能是一个 Bug，请截图并[反馈给开发者](https://github.com/celesWuff/waterctl)。

调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B06873030B003258240601170954F80100
RXD: FDFD09AE79000003936303040506070809101112
TXD: FEFE09BC0000
TXD: FEFE09BB01010D00501403240601235812002000
TXD: FEFE09B2017F99FF0010512406012358130F2700

**Comment by Rin313** [comment]
等待时间似乎太长了。

如果该问题反复发生，这可能是一个 Bug，请截图并[反馈给开发者](https://github.com/celesWuff/waterctl)。

调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B0B000000B0031EC240602194559000000
RXD: FDFD09AE4000C717845203040506070809101112
TXD: FEFE09BC0000
TXD: FEFE09BB01010D00502111240602195313002000
TXD: FEFE09B201A8C7FF0027022406021953140F2700

**Comment by Goumuzee** [comment]
调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B0990D020B003E49240602003215BA0000
RXD: FDFD09AE4800005F654303040506070809101112
TXD: FEFE09BC0000
TXD: FEFE09BB01010D00500267240602195614002000
TXD: FEFE09B2012941FF0005242406021956140F2700

**Comment by emoceilings** [comment]
佛大用不了了，我还以为我手机的问题，舍友说也用不了

**Comment by celesWuff** [comment]
标题绷不住了，我是客服吗

**Comment by Yingluobaidao** [comment]
> 标题绷不住了，我是客服吗
大佬，带我们走吧。

**Comment by celesWuff** [comment]
#34

**Comment by DZiRK5** [comment]
> 标题绷不住了，我是客服吗

部分人是这样的，大佬别太在意
