### ISSUE TITLE
反馈又用不了了！😭

### ISSUE THREAD

**Issue by greenh12** [celesWuff/waterctl#35]
出现错误
等待时间似乎太长了。

如果该问题反复发生，这可能是一个 Bug，请截图并[反馈给开发者](https://github.com/celesWuff/waterctl)。

调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B0A902000B004290240603223232000000
RXD: FDFD09AE2F000012804203040506070809101112
TXD: FEFE09BC0000
TXD: FEFE09BB01010D00500390240603223730002000
TXD: FEFE09B201BDEEFF0038772406032237310F2700

**Comment by dekingpang** [comment]
调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B00F37050B003E5C240608232825560100
RXD: FDFD09AEA700004C819003040506070809101112
TXD: FEFE09BC0000
TXD: FEFE09BB01010D00503522240609003339002000
TXD: FEFE09B2012F56FF0017572406090033390F2700
