### ISSUE TITLE
1

### ISSUE THREAD

**Issue by kevinzence** [celesWuff/waterctl#36]

**Comment by loevetobir** [comment]
你是个弱智吗，没看到作者前几天的声明？遇到什么情况就只会不经思考情绪化地展现你的言行，还逆天地将真实地点公开。怎么，你是github版的炸弹人，还是说你是敌方间谍来反串的？估计现在这个项目也已经被某某知道了，还不是被你这种低智生物导致的。不懂得如何提问就多去看点书，别来这里秀你那低劣无下限的语言素质。
