### ISSUE TITLE
热水器更新连不上了

### ISSUE THREAD

**Issue by chen-yi-1** [celesWuff/waterctl#38]
调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B03A30020B003381240611220547E00000
RXD: FDFD09AE5200006B695603040506070809101112
TXD: FEFE09BC0000
TXD: FEFE09BB00000000000000240611223920002000
TXD: FEFE09B201BF44FF0000002406112239210F2700

**Comment by celesWuff** [comment]
https://github.com/celesWuff/waterctl/issues/34
