### ISSUE TITLE
出现新错误

### ISSUE THREAD

**Issue by 1291657057** [celesWuff/waterctl#39]
出现错误
水控器拒绝启动。

蓝牙水控器 FOSS 当前不支持您的水控器，请不要重试，多次失败可能造成水控器锁定。
若发生锁定，水控器将拒绝一切传入连接；在通电状态下等待约一小时方可恢复。

请截图并反馈给开发者。

调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B09201000B003B89240702192322000000
RXD: FDFD09AEC7000102951503040506070809101112
TXD: FEFE09AF46000103B264B890FE87000000000000
RXD: FDFD09AF7A010102010203040506070809101112

**Comment by MoonAyanami** [comment]
the same to you，can not connect it

**Comment by celesWuff** [comment]
https://github.com/celesWuff/waterctl/issues/34
