### ISSUE TITLE
水控器拒绝启动。

### ISSUE THREAD

**Issue by I-LOVE-DY** [celesWuff/waterctl#40]
水控器拒绝启动。

蓝牙水控器 FOSS 当前不支持您的水控器，请不要重试，多次失败可能造成水控器锁定。
若发生锁定，水控器将拒绝一切传入连接；在通电状态下等待约一小时方可恢复。

请截图并[反馈给开发者](https://github.com/celesWuff/waterctl)。

调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B07749060B004BE0240716152257B20100
RXD: FDFD09AE6200CA5A910103040506070809101112
TXD: FEFE09AFD000CA5B455E6069FE87000000000000
RXD: FDFD09AF7A010102010203040506070809101112

**Comment by celesWuff** [comment]
https://github.com/celesWuff/waterctl/issues/34
