### ISSUE TITLE
版本更新存在的bug吗

### ISSUE THREAD

**Issue by cmy97610** [celesWuff/waterctl#46]
![Y`N9A42_H2`$R)9Q`$KO{V](https://github.com/user-attachments/assets/d4f050a9-0512-4ead-8e49-f18fbac89462)

**Comment by shiyi88888** [comment]
用不了了 能不能更新一下呀

**Comment by celesWuff** [comment]
这与 #42 似乎是相同问题，之后请在 #42 继续追踪此问题。
