### ISSUE TITLE
出现bug

### ISSUE THREAD

**Issue by ss11qq** [celesWuff/waterctl#48]
调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B01330040B002822241021000632B40000
RXD: FD09AE010081FF683003040506070809101112

**Comment by ss11qq** [comment]
调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B01330040B002822241021000632B40000
RXD: FDFD09AE010081FF683003040506070809101112
TXD: FEFE09AF4F008200CA66BBBEFE87000000000000
RXD: FDFD09AF7A010102010203040506070809101112

**Comment by ss11qq** [comment]
水控器拒绝启动。

蓝牙水控器 FOSS 当前不支持您的水控器，请不要重试，多次失败可能造成水控器锁定。
若发生锁定，水控器将拒绝一切传入连接；在通电状态下等待约一小时方可恢复。

**Comment by celesWuff** [comment]
已修复
