### ISSUE TITLE
错误提示 NotSupportedError: GATT operation failed for unknown reason.

### ISSUE THREAD

**Issue by hyzdatoy** [celesWuff/waterctl#55]
NotSupportedError: GATT operation failed for unknown reason.

是什么呢
（这可能是一个 Bug，请截图并[反馈给开发者](https://github.com/celesWuff/waterctl)。）

**Comment by celesWuff** [comment]
通常单纯因为水控器的固件或硬件太差，或距离太远。重试即可。
已发布 v2.0.5 增加对此异常的说明文本。

**Comment by xiaonanttkx123** [comment]
> 通常单纯因为水控器的固件或硬件太差，或距离太远。重试即可。
> 已发布 v2.0.5 增加对此异常的说明文本。

**Comment by xiaonanttkx123** [comment]
还是不行
