### ISSUE TITLE
等待时间过长

### ISSUE THREAD

**Issue by hyzdatoy** [celesWuff/waterctl#56]
等待时间似乎太长了。

如果该问题反复发生，这可能是一个 Bug，请截图并[反馈给开发者](https://github.com/celesWuff/waterctl)。

调试信息：
TXD: FEFE09B001010000
RXD: FDFD09B034D2030B002820241121181636920100
RXD: FDFD09AEB10001FF733403040506070809101112
TXD: FEFE09AF4100020043F89662FE87000000000000

**Comment by celesWuff** [comment]
这是已经修复的问题。请在联网状态下刷新，以更新至 v2.0.4 或更新版本（如果有）。

**Comment by xiaonanttkx123** [comment]
> 这是已经修复的问题。请在联网状态下刷新，以更新至 v2.0.4 或更新版本（如果有）。

**Comment by xiaonanttkx123** [comment]
.
