### ISSUE TITLE
，

### ISSUE THREAD

**Issue by 1433834531** [celesWuff/waterctl#6]
![Screenshot_2022-11-02-11-33-23-917_com android chrome](https://user-images.githubusercontent.com/117244275/199400394-19ba1cdd-0e43-4b26-8e5a-8a7efa95f28f.jpg)
。

**Comment by celesWuff** [comment]
已修复

**Comment by 1433834531** [comment]
大佬，学校热水器升级了，还能出手吗



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 2, 2022 16:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [celesWuff/waterctl] ， (Issue #6)




 
Closed #6 as completed.

**Comment by celesWuff** [comment]
🉑

https://github.com/celesWuff/waterctl/issues/15#issuecomment-2078963008
