### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Kyakui** [celesWuff/waterctl#8]
先感谢大大的脚本。
这里想请教一下这个脚本和蓝牙水控通信的内容是什么，就是具体发了什么给蓝牙水控让它开启、关闭，代码没看懂（我太菜了），我想在单片机上复刻一下功能。

**Comment by celesWuff** [comment]
通信使用的是 BLE。主机在连接到设备后，通过在 `0xF1F0` service，`0xF1F1` characteristic 发送数据，来进行开启和关闭。

关于 BLE 协议的细节，可以参考这篇文章：http://doc.iotxx.com/index.php?title=BLE%E6%8A%80%E6%9C%AF%E6%8F%AD%E7%A7%98

---
开启水控的 payload 可以在 `makePayload` 中找到，即：
```
0xFE, 0xFE, 0x09, 0xB2,
0x01, checksum & 0xFF, checksum >> 8, 0x00,
0x70, 0xE2, 0xEB, 0x20,
0x01, 0x01, 0x00, 0x00,
0x00, 0x6C, 0x30, 0x00
```

其中第六、七字节为从设备名称计算出的校验码。具体算法是，取设备名称的最后五位数字，即“Water”之后的部分，以其 ASCII 码计算 CRC-16。

该 CRC-16 使用了一组非常特殊的参数，具体如下：
```
width=16 poly=0x8005 init=0xe808 refin=true refout=true xorout=0x0000
```

我代码中的 `crc16changgong` 函数即是该 CRC-16 一个最精简的实现。你应该能够很容易地将这部分改写为 C/C++ 代码。

将计算出的 CRC-16 值填充到 payload 时，需要转换为小端，即 `checksum & 0xFF, checksum >> 8`，交换两个字节的位置。

---
关闭水控的 payload 很简单，只需向该 characteristic 发送固定数据 `0xFE, 0xFE, 0x09, 0xB3, 0x00, 0x00`。

之后，设备会主动断开连接，但我仍建议你（在主机这一侧）执行 disconnect。

**Comment by celesWuff** [comment]
如果没有其他问题的话，我就先关闭了。
